services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=https://grafana.affiliapass.com
     - GF_SECURITY_ADMIN_USER=betpassoficial
     - GF_SECURITY_ADMIN_PASSWORD=teste
    ports:
     - '3000:3000'
    volumes:
     - /mnt/data:/var/lib/grafana
volumes:
  grafana_storage: {}